# User gnome settings.
#
# Gnome configuration is managed by dconf, which is a configuration system
# backed a binary database mechanism. To use text-based configuration, do:
#
# Dump settings to an ini file:
#   dconf dump / > dump.ini
#
# Override settings from an ini file:
#   dconf load / < settings.ini

[org/gnome/desktop/wm/keybindings]
close=['<Super>x']
maximize=['<Super>k']
minimize=@as []
move-to-workspace-1=['<Shift><Super>1']
move-to-workspace-2=['<Shift><Super>2']
move-to-workspace-3=['<Shift><Super>3']
move-to-workspace-4=['<Shift><Super>4']
move-to-workspace-last=['<Shift><Super>e']
switch-group=@as []
switch-group-backward=@as []
switch-to-workspace-1=['<Super>1']
switch-to-workspace-2=['<Super>2']
switch-to-workspace-3=['<Super>3']
switch-to-workspace-4=['<Super>4']
switch-to-workspace-last=['<Alt>e']
switch-to-workspace-left=['<Super>p']
switch-to-workspace-right=['<Super>n']
unmaximize=['<Super>j']

[org/gnome/desktop/wm/preferences]
button-layout='icon:minimize,maximize,close'
num-workspaces=5
