# Cheatsheet
#
# TPM: https://github.com/tmux-plugins/tpm
# reference: https://github.com/dreamsofcode-io/tmux/blob/main/tmux.conf
# plugins: https://github.com/tmux-plugins/list?tab=readme-ov-file
#
## Meta
# View bindings: <prefix> ?
# Reload confie: <prefix> :source ~/.tmux.conf
# Install plugins: <prefix> I
# Uninstall plugins: <prefix> alt + u
# Update plugins: <prefix> U

# Fix colors
unbind-key -a
source-file ~/.config/tmux/reset.conf

# Close Window
# bind q killp

# Enable mouse
set -g mouse on

# Change prefix to: ctrl-space
unbind C-b
set -g prefix C-space  # or C-space
bind M-a send-prefix

# Use Alt-arrow keys without prefix key to switch panes
bind l select-pane -L
bind h select-pane -R
bind k select-pane -U
bind j select-pane -D

# Resize
bind -n M-L resize-pane -R 2
bind -n M-H resize-pane -L 2
bind -n M-K resize-pane -U 2
bind -n M-J resize-pane -D 2

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Jump
bind a last-window

#################
# start plugins #
#################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set-option -g @plugin 'b0o/tmux-autoreload'
set -g @plugin 'tmux-plugins/tmux-sessionist'

# start theme #

# https://github.com/catppuccin/tmux?tab=readme-ov-file#status
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_modules_right "directory user host session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{pane_current_path}"

# end theme #

set -g @plugin 'ofirgall/tmux-window-name'

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-boot 'on'
# set -g @continuum-restore 'on'

###############
# end plugins #
###############

# copy stuff
set -g @plugin 'tmux-plugins/tmux-yank'
set -g set-clipboard on
set -g @override_copy_command 'xclip -i -selection clipboard'
set -g @yank_selection 'clipboard'
set -as terminal-features ',*:clipboard'

# copy mode set vi-mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip"
# set -g @yank_selection 'clipboard' # or 'secondary' or 'primary'

# Keep same cwd on split
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# https://github.com/arl/gitmux
# set -g status-right '#(gitmux "#{pane_current_path}")'


##################
# plugin manager #
##################

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# Proper colors
set-option -ga terminal-overrides ",xterm-256color:Tc"
